export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export LC_ALL=en_GB.UTF-8
export PATH=${PATH}:/usr/local/bin
export PATH=${PATH}:/usr/local/sbin
export BASH_SILENCE_DEPRECATION_WARNING=1
alias ls='ls -lpo'
alias ll='ls -la'
alias gits='git status && git branch'
alias gita='git add .'
alias giti='git rm -r --cached . && git add . && git commit -m "Updated gitignore" && git push'
alias gitm='git push && git checkout master && git merge develop && git push && git checkout develop'
