export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
export LC_ALL=en_US.UTF-8
alias ls='ls -lpo'
alias ll='ls -la'
alias gits='git status && git branch'
alias gita='git add .'
alias giti='git rm -r --cached . && git add . && git commit -m "Updated gitignore" && git push'
alias gitm='git push && git checkout master && git merge develop && git push && git checkout develop'
export PATH=${PATH}:/usr/local/bin
export PATH=${PATH}:/usr/local/sbin
export PATH=${PATH}:/usr/local/mysql/bin
export PATH=${PATH}:/usr/local/Cellar/rabbitmq/3.8.2/sbin
export PATH=${PATH}:/usr/local/Cellar/mongodb-community-shell/4.2.0/bin
export PATH=${PATH}:/Library/Developer/android-sdk
export PATH=${PATH}:/Library/Developer/android-sdk/platform-tools
export PATH=${PATH}:/Library/Developer/android-sdk/emulator
export PATH=${PATH}:/Library/Developer/android-sdk/tools
export PATH=${PATH}:/Library/Developer/Flutter/bin
export PATH=${PATH}:/Users/Lazar/.composer/vendor/bin
export PATH=${PATH}:/Library/TeX/texbin
export PATH=${PATH}:/opt/apache-maven-3.8.1/bin
export BASH_SILENCE_DEPRECATION_WARNING=1
source ~/.git-completion.bash
